name: blog-rz

on:
  push:
#    branches: [ logan ]
#    paths:
#      - 'Dockerfile'
#      - 'index.js'
#      - 'index.min.js'
#      - 'package.json'
#      - '.github/workflows/blog-cc.yml'
    tags:
      - 'v**'  # 当推送 v1.0.0 这样的 tag 时触发, 需要在包含此workflow文件的节点上打标签, 对于当前项目需要在主分支打标签并推送
  workflow_dispatch: # 允许手动触发 仅在默认分支(Default Branch)上生效, 若其他分支有相同的workflow文件则可以选择分支手动执行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # 拉取logan分支的代码
        with:
          ref: logan

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-EN
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/blog-rz:3.2.2
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=HTTP Server
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
